networks:
  app-network:

volumes:
  app-data:

services:
  dbvs:
    image:
      "mysql:latest"
    environment:
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "user"
      MYSQL_ROOT_PASSWORD: "root"
      TZ: "Europe/Vilnius"
    ports:
      - "3306:3306/tcp"
    volumes:
      - "./db/data/mysql:/var/lib/mysql"
    networks:
      app-network:

  phpmyadmin:
    image:
      "phpmyadmin:latest"
    environment:
      PMA_USER: "root"
      PMA_PASSWORD: "root"
      PMA_HOST: "dbvs"
    ports:
      - "8080:80/tcp"
    links:
      - "dbvs:db"
    networks:
      app-network:
